project: http-server
website: https://http-server.cli.jaden.tech
profiles:
- name: dev
- name: review
sessions:
- role: ops
  profile: ops
  title: http-server-ops
- role: dev
  profile: dev
  title: http-server-dev
- role: review
  profile: review
  title: http-server-review
handoff:
  enabled: true
  doc: documents/handoff/handoff-http-server-review.md
  updated_at: '2026-08-23'
